version: "3.1"
services:
  mysql:
    image: mysql:8
    container_name: books-manager-mysql
    working_dir: /application
    volumes:
      - .:/application
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=password
    ports:
      - "8002:3306"
  webserver:
    image: nginx:alpine
    container_name: books-manager-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - "mysql:mysql"
  php-fpm:
    build: docker/php-fpm
    container_name: books-manager-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
  composer:
    image: "composer"
    container_name: books-manager-composer
    working_dir: /application
    volumes:
      - .:/application

volumes:
  data: